### ISSUE TITLE
Support for S5 port

### ISSUE THREAD

**Issue by michalvi** [DexterInd/BrickPi_Python#55]
Why there is no support for sensor port S5 in BrickPi libraries? Why is it physically there if it's not supported?
![BrickPiReference](https://cdn.sparkfun.com/r/600-600/assets/b/7/2/9/9/Brick_Pi_Hookup_Guide-06.jpg)

**Comment by DexterInd** [comment]
Hey Michalvi, it's a direct I2C link to the Pi.  The other sensor ports connect to the Pi through the BrickPi chips.  The S5 connects directly to the Pi (the I2C lines connect directly to the Pi).  So if you have an I2C sensor you want to connect directly to the Pi, that's a great way to do it.

This was more of an advanced sensor port that very few folks used.  You can see on the latest version of the hardware, we've removed it since there's been no interest.

**Comment by DexterInd** [comment]
You can see an example of how to use it in this code:  https://github.com/DexterInd/BrickPi_Python/blob/master/Sensor_Examples/dIMU_on_Sensor_5.py

**Comment by michalvi** [comment]
This is actually very helpful. Thank you.
